FROM registry.ci.openshift.org/ocp/4.20:base-rhel9 AS ui-build
USER 0


COPY --chown=1001:0 . /app
ENV NODE_OPTIONS='--max-old-space-size=8192'
RUN git config --global --add safe.directory /app

# The REMOTE_SOURCES value is set by the build system to indicate the location of the cachito-backed artifacts cache.
# As cachito might not be available in all environments, we need to make sure the value is set before trying to use it and
# that the COPY layer below doesn't fail. Setting it to be the Dockerfile itself is fairly safe, as it will always be
# available.

COPY $REMOTE_SOURCES $REMOTE_SOURCES_DIR
RUN touch $REMOTE_SOURCES_DIR/cachito-gomod-with-deps/app/registry-ca.pem $REMOTE_SOURCES_DIR/cachito-gomod-with-deps/app/.npmrc $REMOTE_SOURCES_DIR/cachito-gomod-with-deps/app/.yarnrc
WORKDIR /app

ARG YARN_VERSION=3.4.1

RUN dnf module install -y nodejs:16/development
RUN yarn config set nodedir /usr
RUN yarn install --immutable && yarn build:all

FROM registry.access.redhat.com/ubi9/go-toolset:1.22 as proxy-build
WORKDIR /app
COPY apps/assisted-disconnected-ui/proxy /app
USER 0
# Build using vendored deps as build system does not have internet access
RUN export GOFLAGS="-mod=vendor"; go build

FROM registry.ci.openshift.org/ocp/4.20:base-rhel9
COPY --from=ui-build /app/apps/assisted-disconnected-ui/build /app/proxy/dist
COPY --from=proxy-build /app/assisted-disconnected-ui /app/proxy
WORKDIR /app/proxy
EXPOSE 8080
CMD ./assisted-disconnected-ui
